### ISSUE TITLE
TO-DO v1.2.0

### ISSUE THREAD

**Issue by dleitee** [dleitee/strman#21]
- [x] Documentation Improvement #29 
- [x] Length improvement 9556c3a28fb4a2526463ce845fac38f4e292ea92
- [x] Functions
  - [x] format 9d38fc21e9755d018e9d716dc2987ce7736ac911
  - [x] trim(string, char), leftTrim(string, char), rightTrim(string, char) a0828f28c33fab5c308e9064fb63f5d2e617b752
  - [x] removeEmptyStrings 46fee001acf88433cbccf56104e78c7148561e05
  - [x] compare 05dd92693ccb9915b89ae08a246811736ef88553
  - [x] equal dda2c6a73b97277c566e0c7b5a405c901fd777cf
  - [x] inequal a8297f1
  - [x] hexEncode 89a2d8120896ae6a5154ad5b7e0fb59f7a63cb14
  - [x] hexDecode 1644ac50a74f7e0456b3a4d9f7adfb41d3c13e18
  - [x] decEncode 18399cb
  - [x] decDecode d937e8d
  - [x] binEncode 3331ce6
  - [x] binDecode 57d9865
  - [x] htmlEncode f998ac1
  - [x] htmlDecode f998ac1
  - [x] urlEncode bc9474c
  - [x] urlDecode bc9474c
  - [x] base64Encode 81bc11e
  - [x] base64Decode 81bc11e

If you have other ideas, please document them in this issue.

**Comment by sergiors** [comment]
I think leftTrim and rightTrim should have the same signature

**Comment by dleitee** [comment]
@sergiors without char parameter?

**Comment by sergiors** [comment]
Nope, before my comment, leftTrim and rightTrim, params order was reversed 👯

**Comment by dleitee** [comment]
hahaha was my mistake when typing :sweat:
