### ISSUE TITLE
strman v2.0.0

### ISSUE THREAD

**Issue by dleitee** [dleitee/strman#58]
- [x]  #59 Create multiple packages, basically one for each function. #59
- [x] #60 Possibility to install functions separately using` npm install strman.replace` for example.
- [x] #61 Each function should return a StrmanType that contains all functions of project, thereby we could make function chains, the result of all functions on the chain should be a string.
- [x] #62 Update TravisCI to publish project on npm when there a new merge on branch master
- [x] #63 Create a new website
